MedicalSystemMvc/Models/PatientViewModel.cs
using MedicalSystemClassLibrary.Models;
using System.ComponentModel.DataAnnotations;

namespace MedicalSystemMvc.Models
{
    public class PatientViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "First name is required")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Last name is required")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "OIB is required")]
        public string OIB { get; set; }

        [Required(ErrorMessage = "DOB is required")]
        public DateTime DateOfBirth { get; set; }

        [Required(ErrorMessage = "Gender is required")]
        public string Gender { get; set; }

        public ICollection<MedicalRecordViewModel> MedicalRecords { get; set; } = new List<MedicalRecordViewModel>();

        public ICollection<PrescriptionViewModel> Prescriptions { get; set; } = new List<PrescriptionViewModel>();

        public ICollection<ExaminationViewModel> Examinations { get; set; } = new List<ExaminationViewModel>();
    }
}

MedicalSystemMvc/Controllers/ExaminationController.cs
using Microsoft.AspNetCore.Mvc;
using MedicalSystemMvc.Models;
using MedicalSystemClassLibrary.Data;
using MedicalSystemClassLibrary.Models;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using MedicalSystemClassLibrary.Enums;
using System.Collections.Generic;
using MedicalSystemClassLibrary.Dictionaries;

namespace MedicalSystemMvc.Controllers
{
    public class ExaminationController : Controller
    {
        private readonly MedicalSystemDbContext _context;

        public ExaminationController(MedicalSystemDbContext context)
        {
            _context = context;
        }

        // GET: Examination
        public async Task<IActionResult> Index()
        {
            var examinations = await _context.Examinations.ToListAsync();
            return View(examinations);
        }

        // GET: Examination/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var examination = await _context.Examinations
                .FirstOrDefaultAsync(m => m.Id == id);
            if (examination == null)
            {
                return NotFound();
            }

            return View(examination);
        }

        // GET: Examination/Create
        public IActionResult Create(int? patientId)
        {
            var viewModel = new ExaminationViewModel
            {
                Date = DateTime.UtcNow // Set Date to DateTime.UtcNow by default
            };
            if (patientId.HasValue)
            {
                viewModel.PatientId = patientId.Value;
            }
            ViewBag.ExaminationTypes = ExaminationTypeDict.Descriptions;
            return View(viewModel);
        }

        // POST: Examination/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ExaminationViewModel model)
        {
            if (ModelState.IsValid)
            {
                // Convert Date to UTC
                model.Date = DateTime.SpecifyKind(model.Date, DateTimeKind.Utc);

                var examination = new Examination
                {
                    Date = model.Date,
                    Type = model.Type.ToString(),
                    PatientId = model.PatientId
                };

                _context.Add(examination);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.ExaminationTypes = ExaminationTypeDict.Descriptions;
            return View(model);
        }

        // GET: Examination/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var examination = await _context.Examinations.FindAsync(id);
            if (examination == null)
            {
                return NotFound();
            }

            var model = new ExaminationViewModel
            {
                Id = examination.Id,
                Date = examination.Date,
                Type = Enum.Parse<ExaminationType>(examination.Type),
                PatientId = examination.PatientId
            };

            ViewBag.ExaminationTypes = ExaminationTypeDict.Descriptions;
            return View(model);
        }

        // POST: Examination/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ExaminationViewModel model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var examination = await _context.Examinations.FindAsync(id);
                    if (examination == null)
                    {
                        return NotFound();
                    }

                    // Convert Date to UTC
                    model.Date = DateTime.SpecifyKind(model.Date, DateTimeKind.Utc);

                    examination.Date = model.Date;
                    examination.Type = model.Type.ToString();
                    examination.PatientId = model.PatientId;

                    _context.Update(examination);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ExaminationExists(model.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewBag.ExaminationTypes = ExaminationTypeDict.Descriptions;
            return View(model);
        }

        // GET: Examination/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var examination = await _context.Examinations
                .FirstOrDefaultAsync(m => m.Id == id);
            if (examination == null)
            {
                return NotFound();
            }

            return View(examination);
        }

        // POST: Examination/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var examination = await _context.Examinations.FindAsync(id);
            if (examination == null)
            {
                return NotFound();
            }

            _context.Examinations.Remove(examination);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ExaminationExists(int id)
        {
            return _context.Examinations.Any(e => e.Id == id);
        }
    }
}

MedicalSystemMvc/Controllers/PrescriptionController.cs
using Microsoft.AspNetCore.Mvc;
using MedicalSystemMvc.Models;
using MedicalSystemClassLibrary.Data;
using MedicalSystemClassLibrary.Models;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace MedicalSystemMvc.Controllers
{
    public class PrescriptionController : Controller
    {
        private readonly MedicalSystemDbContext _context;

        public PrescriptionController(MedicalSystemDbContext context)
        {
            _context = context;
        }

        // GET: Prescription
        public async Task<IActionResult> Index()
        {
            var prescriptions = await _context.Prescriptions
                .Select(p => new PrescriptionViewModel
                {
                    Id = p.Id,
                    Medication = p.Medication,
                    Dosage = p.Dosage,
                    PatientId = p.PatientId
                })
                .ToListAsync();

            return View(prescriptions);
        }

        // GET: Prescription/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var prescription = await _context.Prescriptions
                .Where(p => p.Id == id)
                .Select(p => new PrescriptionViewModel
                {
                    Id = p.Id,
                    Medication = p.Medication,
                    Dosage = p.Dosage,
                    PatientId = p.PatientId
                })
                .FirstOrDefaultAsync();

            if (prescription == null)
            {
                return NotFound();
            }

            return View(prescription);
        }

        // GET: Prescription/Create
        public IActionResult Create(int? patientId)
        {
            var viewModel = new PrescriptionViewModel();
            if (patientId.HasValue)
            {
                viewModel.PatientId = patientId.Value;
            }
            return View(viewModel);
        }

        // POST: Prescription/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PrescriptionViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var prescription = new Prescription
                {
                    PatientId = viewModel.PatientId,
                    Medication = viewModel.Medication,
                    Dosage = viewModel.Dosage
                };
                _context.Add(prescription);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }

        // GET: Prescription/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var prescription = await _context.Prescriptions.FindAsync(id);
            if (prescription == null)
            {
                return NotFound();
            }

            var model = new PrescriptionViewModel
            {
                Id = prescription.Id,
                Medication = prescription.Medication,
                Dosage = prescription.Dosage,
                PatientId = prescription.PatientId
            };

            return View(model);
        }

        // POST: Prescription/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, PrescriptionViewModel model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var prescription = await _context.Prescriptions.FindAsync(id);
                if (prescription == null)
                {
                    return NotFound();
                }

                prescription.Medication = model.Medication;
                prescription.Dosage = model.Dosage;
                prescription.PatientId = model.PatientId;

                _context.Update(prescription);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: Prescription/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var prescription = await _context.Prescriptions
                .Where(p => p.Id == id)
                .Select(p => new PrescriptionViewModel
                {
                    Id = p.Id,
                    Medication = p.Medication,
                    Dosage = p.Dosage,
                    PatientId = p.PatientId
                })
                .FirstOrDefaultAsync();

            if (prescription == null)
            {
                return NotFound();
            }

            return View(prescription);
        }

        // POST: Prescription/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var prescription = await _context.Prescriptions.FindAsync(id);
            if (prescription == null)
            {
                return NotFound();
            }

            _context.Prescriptions.Remove(prescription);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

MedicalSystemMvc/Views/Patient/Create.cshtml
@model MedicalSystemMvc.Models.PatientViewModel

@{
    ViewData["Title"] = "Create Patient";
}

<h1>Create Patient</h1>

<h4>Patient</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OIB" class="control-label"></label>
                <input asp-for="OIB" class="form-control" />
                <span asp-validation-for="OIB" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label"></label>
                <input asp-for="DateOfBirth" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
                <br />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

MedicalSystemMvc/Views/Patient/Delete.cshtml
@model MedicalSystemMvc.Models.PatientViewModel

@{
    ViewData["Title"] = "Delete Patient";
}

<h1>Delete Patient</h1>

<h4>Patient</h4>
<hr />
<div>
    <h4>Are you sure you want to delete this?</h4>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.OIB)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OIB)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
    </dl>

    <form asp-action="Delete" method="post">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MedicalSystemMvc/Views/Patient/Details.cshtml
@model MedicalSystemMvc.Models.PatientViewModel

@{
    ViewData["Title"] = "Patient Details";
}

<h1>Patient Details</h1>

<div>
    <h4>Patient</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.OIB)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OIB)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
    </dl>
</div>

<div>
    <h4>
        Medical Record
        <a asp-action="Create" asp-controller="MedicalRecord" asp-route-patientId="@Model.Id" class="btn btn-primary">Add Medical Record</a>
    </h4>
    <hr />
    <ul>
        @foreach (var medicalRecord in Model.MedicalRecords)
        {
            <li>@medicalRecord.DiseaseName -> @medicalRecord.StartDate - @medicalRecord.EndDate</li>
        }
    </ul>
</div>

<div>
    <h4>
        Prescriptions
        <a asp-action="Create" asp-controller="Prescription" asp-route-patientId="@Model.Id" class="btn btn-primary">Add Prescription</a>
    </h4>
    <hr />
    <ul>
        @foreach (var prescription in Model.Prescriptions)
        {
            <li>@prescription.Medication - @prescription.Dosage</li>
        }
    </ul>

</div>

<div>
    <h4>
        Examinations
        <a asp-action="Create" asp-controller="Examination" asp-route-patientId="@Model.Id" class="btn btn-primary">Add Examination</a>
    </h4>
    <hr />
    <ul>
        @foreach (var examination in Model.Examinations)
        {
            <li>@examination.Date.ToShortDateString() - @ViewBag.ExaminationTypes[examination.Type]</li>
        }
    </ul>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a> |
    <a asp-action="ExportToCsv" asp-route-id="@Model.Id" class="btn btn-success">Export as CSV</a>
</div>

MedicalSystemMvc/Views/Patient/Edit.cshtml
@model MedicalSystemMvc.Models.PatientViewModel

@{
    ViewData["Title"] = "Edit Patient";
}

<h1>Edit Patient</h1>

<h4>Patient</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div class="form-group">
                <input type="hidden" asp-for="Id" />
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OIB" class="control-label"></label>
                <input asp-for="OIB" class="form-control" />
                <span asp-validation-for="OIB" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label"></label>
                <input asp-for="DateOfBirth" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

MedicalSystemMvc/Views/Patient/Index.cshtml
@model IEnumerable<MedicalSystemMvc.Models.PatientViewModel>

@{
    ViewData["Title"] = "Patients";
}

<h1>Patients</h1>

<form asp-action="Index" method="get">
    <div class="form-group">
        <label for="searchString">Search by Last Name or OIB</label>
        <input type="text" class="form-control" id="searchString" name="searchString" value="@ViewData["CurrentFilter"]" />
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Search</button>
</form>

<div class="mt-3">
    <a asp-action="Create" class="btn btn-success">Create New Patient</a>
</div>

@if (ViewData["CurrentFilter"] != null)
{
    if (!Model.Any())
    {
        <p>No patients found. Please enter a search term.</p>
    }
    else
    {
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.First().FirstName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.First().LastName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.First().OIB)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.First().DateOfBirth)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.First().Gender)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.FirstName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.LastName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.OIB)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DateOfBirth)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Gender)
                        </td>
                        <td>
                            <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
}